apiVersion: v1
kind: ServiceAccount
metadata:
  name: chkk-operator-sa
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chkk-operator-manager-role
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - k8s.chkk.io
  resources:
  - chkkagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chkk.io
  resources:
  - chkkagents/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chkk.io
  resources:
  - chkkagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - roles.rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - roles.rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - roles.rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - roles.rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chkk-operator-metrics-reader
  namespace: chkk-system
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chkk-operator-proxy-role
  namespace: chkk-system
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chkk-operator-manager-rolebinding
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chkk-operator-manager-role
subjects:
- kind: ServiceAccount
  name: chkk-operator-sa
  namespace: chkk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chkk-operator-proxy-rolebinding
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chkk-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: chkk-operator-sa
  namespace: chkk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chkk-operator-leader-election-role
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chkk-operator-leader-election-rolebinding
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chkk-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: chkk-operator-sa
  namespace: chkk-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chkk-operator
  namespace: chkk-system
  labels:
    app.kubernetes.io/name: chkk-operator
    app.kubernetes.io/instance: chkk-operator
    app.kubernetes.io/managed-by: kubectl
    control-plane: chkk-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: chkk-operator
  template:
    metadata:
        annotations:
          chkk.io/name: chkk-operator
        labels:
            app.kubernetes.io/name: chkk-operator
            app.kubernetes.io/instance: chkk-operator
            control-plane: chkk-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
                    - amd64
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: amd64
          effect: NoSchedule
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
      containers:
      - args:
        - --leader-elect
        env:
          - name: CHKK_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: chkk-operator
                key: CHKK_ACCESS_TOKEN
        image: "public.ecr.aws/chkk/operator:v0.0.7"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 65534
        runAsUser: 10000
      serviceAccountName: chkk-operator-sa
      terminationGracePeriodSeconds: 10
